# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoshop', models.IntegerField()),
                ('illustrator', models.IntegerField()),
                ('adobexd', models.IntegerField()),
                ('sketch', models.IntegerField()),
                ('indesign', models.IntegerField()),
                ('imposition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=150, unique=True)),
                ('school', models.CharField(max_length=200)),
                ('study_start', models.DateField()),
                ('study_end', models.DateField()),
                ('some_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=45)),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(help_text='age must be positive')),
                ('photo', models.ImageField(upload_to='people_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('statement', models.TextField()),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refereances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=130, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('work_start', models.DateField()),
                ('work_end', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='languageskills',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='interest',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='educationqualifications',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='designskills',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
