# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationqualifications',
            name='education',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languageskills',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='refereances',
            name='company',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='refereances',
            name='director',
            field=models.CharField(max_length=100),
        ),
    ]
