# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20171108_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('web_sourse', models.CharField(max_length=100)),
                ('some_start', models.DateField()),
                ('some_end', models.DateField()),
                ('some_text', models.TextField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='designskills',
            name='photoshop',
            field=models.IntegerField(help_text='sss'),
        ),
    ]
