# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20171109_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageskills',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
