# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20171110_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='human',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='profile.Interest'),
        ),
    ]
