# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20171110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageskills',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_logotype',
            field=models.ImageField(upload_to='work_images/'),
        ),
    ]
