# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20171112_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designskills',
            name='adobexd',
        ),
        migrations.RemoveField(
            model_name='designskills',
            name='illustrator',
        ),
        migrations.RemoveField(
            model_name='designskills',
            name='imposition',
        ),
        migrations.RemoveField(
            model_name='designskills',
            name='indesign',
        ),
        migrations.RemoveField(
            model_name='designskills',
            name='photoshop',
        ),
        migrations.RemoveField(
            model_name='designskills',
            name='sketch',
        ),
        migrations.AddField(
            model_name='designskills',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designskills',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
